# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Blog.

# Short description (goes below the title; it will also be used in the RSS feed)
description: Shawn learns how to use Jekyll. It's surprisingly passable.

# Your name, as you want it to appear underneath each post and in the footer
author: karmeleonnn

# Your email if you want it to be linked on the contact page
author_email: shawn@yelp.com

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://karmeleon.github.io

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Tell Jekyll that I have scss
sass:
    sass_dir: _scss
    style: compressed

# Finally get pagination to work
paginate: 5

# SEO tag stuff
twitter:
  username: karmeleonnn

logo: /assets/favicon.png

social:
  name: Shawn Walton
  links:
    - https://twitter.com/karmeleonnn
    - https://www.facebook.com/karmeleonnn
    - https://github.com/karmeleon
    - https://www.linkedin.com/in/shawn-walton-7582838a/
    - https://karmeleon.yelp.com

google_site_verification: gtNWNpq10URnsd3lLUsbqcViEFe_r4lREE9UaULnBwk

gems: [jekyll-paginate, jekyll-seo-tag, jekyll-redirect-from]